
const counts=[["4","Families"],["317","People"],["11","Generations"],["58","Stories"],["1,842","Photos"],["623","Sources"],["19","Places"],["31","Mysteries"]];
const rooms={
families:{k:"Family Assembly",t:"Four family lines",i:"Balanced introductions—people first, records second.",c:`<div class="family-grid"><article class="panel family-panel" data-family="Zahner"><small>Zahner</small><h3>Baden origins and American chapters</h3><p>Mining, farming, aviation, movement, and family enterprise.</p></article><article class="panel family-panel" data-family="Downing"><small>Downing</small><h3>Working lives and communities</h3><p>Factory workers, farmers, laborers, households, and practical family life.</p></article><article class="panel family-panel" data-family="Blackwell"><small>Blackwell</small><h3>Faith, land, and public life</h3><p>Preachers, public figures, farming, property, influence, and carefully researched history.</p></article><article class="panel family-panel" data-family="Barrett"><small>Barrett</small><h3>Trades, businesses, and relationships</h3><p>Including Bill Barrett’s decades behind the barber chair.</p></article></div>`},
wanderings:{k:"Wanderings",t:"The family atlas",i:"Documented places, family leads, and locations still waiting to be identified.",c:`<div class="map-shell"><div class="atlas"><svg viewBox="0 0 1000 560"><rect width="1000" height="560" fill="#d8c6a6"/><path d="M70 95C145 35 255 40 310 91C344 123 335 163 300 188C260 215 218 191 185 212C143 239 98 213 76 173C58 140 42 117 70 95Z" fill="#87957a"/><path d="M496 91C555 52 653 55 711 90C746 112 750 148 718 173C688 198 648 181 618 202C584 226 536 207 515 176C490 142 466 112 496 91Z" fill="#87957a"/><path d="M565 149C470 154 387 169 292 213" fill="none" stroke="#a4553d" stroke-width="4" stroke-dasharray="10 8"/><circle cx="565" cy="149" r="10" fill="#394b3c"/><circle cx="292" cy="213" r="10" fill="#ba914a"/><text x="582" y="143" font-family="Georgia" font-size="19">Kenzingen, Baden</text><text x="206" y="243" font-family="Georgia" font-size="19">American chapters</text></svg></div><aside class="panel legend"><h3>Places loaded</h3><button><b>Kenzingen, Baden</b><br><small>Documented · Zahner · October 1860</small></button><button><b>American Zahner chapters</b><br><small>Research framework</small></button><button><b>Blackwell family property</b><br><small>Family lead · evidence needed</small></button><button><b>Bill Barrett’s barber shop</b><br><small>Location needed</small></button></aside></div>`},
album:{k:"Album",t:"Photographs and objects",i:"A visual collection designed for identification, context, and family contribution.",c:`<div class="photo-grid">${["Zahner portraits","Downing households","Blackwell photographs","Barrett family album","Unidentified people","Workplaces and tools","Homes and property","Documents and keepsakes"].map(x=>`<article class="photo-card">${x}<br>Photographs will appear here</article>`).join("")}</div>`},
livelihoods:{k:"Lives & Livelihoods",t:"The images come from the lives",i:"Occupations guide the visual language without defining an entire family.",c:`<div class="livelihood-grid">${[["In the Air","Zahner pilots through licenses, aircraft, airfields, uniforms, and memories."],["Beneath the Ground","Mining through lamps, maps, tools, company towns, payrolls, and movement."],["The Land","Farming across all four lines through deeds, acreage, crops, livestock, and weather."],["Factory & Labor","Machinery, factory buildings, work clothes, neighborhoods, and routines."],["Pulpit & Public Life","Churches, sermons, campaigns, notices, meetings, and local influence."],["The Barber Chair","Bill Barrett’s shop through chairs, razors, signs, customers, and memory."]].map(x=>`<article class="panel"><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join("")}</div>`},
stories:{k:"Narrated Stories",t:"Read it. Hear it remembered.",i:"Stories keep fact, memory, interpretation, and open questions visibly distinct.",c:`<div class="story-grid"><article class="panel"><small>Draft story · Zahner</small><h3>Three days in October</h3><p>A child, a parish register, and the beginning of a trail through Baden.</p><span class="tag">Documented fact</span></article><article class="panel"><small>Narrator Studio</small><h3>Preserve a relative’s voice</h3><p>Future chapters can pair written stories with family recordings.</p></article><article class="panel"><small>Story Builder</small><h3>Evidence before interpretation</h3><p>Records, memories, interpretation, contradictions, and unanswered questions stay separate.</p></article></div>`},
archive:{k:"Archive & Junk Drawer",t:"Everything preserved",i:"Sources, documents, unidentified items, unresolved clues, and materials that do not have a permanent room yet.",c:`<div class="searchbar"><input id="archiveSearch" placeholder="Search the archive"></div><div class="archive-grid">${[["People","317 named entries"],["Sources","623 citations and records"],["Photographs","1,842 images planned"],["Places","19 mapped or pending"],["Stories","58 published or planned"],["Mysteries","31 unresolved clues"]].map(x=>`<article class="panel archive-item"><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join("")}</div>`}
};
const entrance=document.getElementById("entrance"),room=document.getElementById("room"),inventory=document.getElementById("inventory");
document.getElementById("countGrid").innerHTML=counts.map(x=>`<div class="count"><b>${x[0]}</b><span>${x[1]}</span></div>`).join("");
document.getElementById("inventoryHandle").onclick=()=>inventory.classList.add("open");document.getElementById("closeInventory").onclick=()=>inventory.classList.remove("open");
function openRoom(key){const d=rooms[key];document.getElementById("roomKicker").textContent=d.k;document.getElementById("roomTitle").textContent=d.t;document.getElementById("roomIntro").textContent=d.i;document.getElementById("roomContent").innerHTML=d.c;entrance.classList.remove("active-view");room.classList.add("active-view");history.replaceState(null,"","#"+key);if(key==="archive"){document.getElementById("archiveSearch").oninput=e=>document.querySelectorAll(".archive-item").forEach(i=>i.style.display=i.textContent.toLowerCase().includes(e.target.value.toLowerCase())?"":"none")}}
document.querySelectorAll("[data-room]").forEach(b=>b.onclick=()=>openRoom(b.dataset.room));document.querySelectorAll("[data-family]").forEach(b=>b.onclick=()=>openRoom("families"));document.getElementById("backButton").onclick=()=>{room.classList.remove("active-view");entrance.classList.add("active-view");history.replaceState(null,"",location.pathname)};const hash=location.hash.slice(1);if(rooms[hash])openRoom(hash);
